export const Strings = {
    sign_In:'Sign In',
    sign_Up:'Sign Up',
    login:'Login',
    accessYourAccount:'Access to your account',
    Or:'Or',
    loginWithEmail:'Login with email address',
    loginWithMobile:'Login with mobile number',
    register:'Register',
    verification:'Verification',
    resend:'Resend',
    otpVerificationText:'Please Enter the 4 Digit Code Sent To',
    phoneNumber : "Phone Number",
    emailAddress :'Email Address',
    verify:'Verify',
    chooseYourService:"Choose Your Service",
    forgotPassword:' Forget Password?',
    forgotReceiveVerification:"Please Enter Your Email Address To Receive a Verification Code.",
    send:'Send',
    setNewPassword:'Set New Password',
    yourNewPasswordDifferent:"Your New Password Must Be Different from Previously Used Password.",
    save:'Save',
    personalInformation :'Personal Information',
    tellUsAboutYourself:'Tell us about yourself',
    continue:'Continue',
    goToDashborad:'Go To Dashboard',
    next:'Next',
    upload:'Upload',
    drivingLicence:'Driving Licence',
    paymentMethod:'Payment Method',
    adhaarCard:'Aadhaar Card',
    panCard:'PAN Card',
    registrationCertificate:'Registration Certificate (RC)',
    vehicleInsurance:"Vehicle Insurance",
    policeClearanceCertificate:'Police Clearance Certificate (PCC)',
    uploadFrontSideOfDL:'Upload front side of DL',
    uploadBackSideOfDL:'Upload back side of DL',
    profilePhoto:"Profile Photo",
    makeVisibleGlare:"Make sure your photo is entirely visible, glare free and not blurred.",
    uploadFrontSideOfAadhar:'Upload front side of Aadhaar',
    uploadBackSideOfAadhar:'Upload back side of Aadhaar',
    uploadFrontSideOfPANCard:"Upload front side of PAN Card",
    uploadBackSideOfPANCard:'Upload back side of PAN Card',
    uploadFrontSideOfRC:'Upload front side of RC',
    uploadBackSideOfRC:'Upload back side of RC',
    uploadYourVehicleInsurance:'Upload your vehicle insurance',
    uploadYourPCC:'Upload your PCC',
    welcome:'Welcome,',
    chooseYourVehicleType:'Choose your vehicle type',
    TellUsLoveAbout :'Tell us what you love about the app, or what we could be doing better.'



}