export const orderArray = 
[
  {
      "__v": 0,
      "_id": "685a8366fe1a10af4256c786",
      "addon_notes": "",
      "admin_pay_amt": 90,
      "after_discount_sub_amt": 90,
      "amount_recived": 100,
      "cart_id": "685a8341fe1a10af4256c607",
      "cart_items": [Array
      ],
      "cooking_time": "45 minutes",
      "coupon_amount": 5,
      "coupon_code": "DISCOUNT20",
      "createdAt": "2025-06-24T10:52:22.777Z",
      "customer_id": "674004448c0213057bd1519c",
      "delivery_address": [Object
      ],
      "delivery_instructions": [Object
      ],
      "delivery_time": "2025-02-15T14:30:00.000Z",
      "dilevery_time": "2025-02-15T14:30:00Z",
      "distance_from_customer": "5.2",
      "invoice_no": "INV123456",
      "item_sub_total_amount": 100.5,
      "notified": 0,
      "order_id": "ORD98765",
      "org_pay_amt": 95,
      "otp": "123456",
      "packing_fee": 5,
      "payment_method_id": "credit_card",
      "reason_of_cancellation": "Customer changed mind",
      "refund_amt": 0,
      "refund_status": "norefund",
      "remaining_balance_amt": 0,
      "restaurant_id": "6788fee87dcbadd89696ecc0",
      "review_skipped": 0,
      "status": "waiting_for_confirmation",
      "tax_amount": 10,
      "total_amount": 677,
      "transaction_id": "pay_Ql0TheeLJH9XgT",
      "updatedAt": "2025-06-24T10:52:22.777Z",
      "verification_code": "VER12345"
  },
  {
      "__v": 0,
      "_id": "685a8362fe1a10af4256c615",
      "addon_notes": "",
      "admin_pay_amt": 90,
      "after_discount_sub_amt": 90,
      "amount_recived": 100,
      "cart_id": "685a8341fe1a10af4256c607",
      "cart_items": [Array
      ],
      "cooking_time": "45 minutes",
      "coupon_amount": 5,
      "coupon_code": "DISCOUNT20",
      "createdAt": "2025-06-24T10:52:18.014Z",
      "customer_id": "674004448c0213057bd1519c",
      "delivery_address": [Object
      ],
      "delivery_instructions": [Object
      ],
      "delivery_time": "2025-02-15T14:30:00.000Z",
      "dilevery_time": "2025-02-15T14:30:00Z",
      "distance_from_customer": "5.2",
      "invoice_no": "INV123456",
      "item_sub_total_amount": 100.5,
      "notified": 0,
      "order_id": "ORD98765",
      "org_pay_amt": 95,
      "otp": "123456",
      "packing_fee": 5,
      "payment_method_id": "credit_card",
      "reason_of_cancellation": "Customer changed mind",
      "refund_amt": 0,
      "refund_status": "norefund",
      "remaining_balance_amt": 0,
      "restaurant_id": "6788fee87dcbadd89696ecc0",
      "review_skipped": 0,
      "status": "waiting_for_confirmation",
      "tax_amount": 10,
      "total_amount": 677,
      "transaction_id": "pay_Ql0TheeLJH9XgT",
      "updatedAt": "2025-06-24T10:52:18.014Z",
      "verification_code": "VER12345"
  }
]
// [
//   {
//     id: 1,
//     trackingId: '0256986327',
//     status: 'Preparing',
//     restaurantName: 'Suraya Fast Food',
//     dishArray: [
//       {
//         id: 1,
//         name: 'Manchurian with Fried Rice',
//         quanity: 2,
//         vegNonVeg: 'veg',
//         price: 170,
//       },
//       {
//         id: 2,
//         name: 'Rumali Roti',
//         quanity: 6,
//         vegNonVeg: 'veg',
//         price: 60,
//       },
//       {
//         id: 3,
//         name: 'Chicken Biriyani',
//         quanity: 1,
//         vegNonVeg: 'nonveg',
//         price: 280,
//       },
//     ],
//     billPayment: 'Paid',
//     date: new Date(),
//     total: 450,
//     cookinTiming:'20 min',
//     instructions:
//       'Please make extra spicy, Please make extra spicy, Please make extra spicy, Please make extra spicy.',
//   },
//   {
//     id: 2,
//     date: new Date(),
//     trackingId: '0256986328',
//     status: 'Packing',
//     restaurantName: 'Suraya Fast Food',
//     dishArray: [
//       {
//         id: 1,
//         name: 'Manchurian with Fried Rice',
//         quanity: 2,
//         vegNonVeg: 'veg',
//         price: 170,
//       },
//       {
//         id: 2,
//         name: 'Rumali Roti',
//         quanity: 6,
//         vegNonVeg: 'veg',
//         price: 60,
//       },
//       {
//         id: 3,
//         name: 'Chicken Biriyani',
//         quanity: 1,
//         vegNonVeg: 'nonveg',
//         price: 280,
//       },
//     ],
//     total: 450,
//     billPayment: 'Unpaid',
//     cookinTiming:'20 min',
//     date: new Date(),
//     instructions:
//       ' Please make extra spicy, Please make extra spicy, Please make extra spicy, Please make extra spicy.',
//   },
//   {
//     id: 3,
//     trackingId: '0256986329',
//     status: 'Ready To Pickup',
//     restaurantName: 'Suraya Fast Food',
//     dishArray: [
//       {
//         id: 1,
//         name: 'Manchurian with Fried Rice',
//         quanity: 2,
//         vegNonVeg: 'veg',
//         price: 170,
//       },
//       {
//         id: 2,
//         name: 'Rumali Roti',
//         quanity: 6,
//         vegNonVeg: 'veg',
//         price: 60,
//       },
//       {
//         id: 3,
//         name: 'Chicken Biriyani',
//         quanity: 1,
//         vegNonVeg: 'nonveg',
//         price: 280,
//       },
//     ],
//     total: 450,
//     billPayment: 'Paid',
//     cookinTiming:'20 min',
//     date: new Date(),
//     instructions:
//       ' Please make extra spicy, Please make extra spicy, Please make extra spicy, Please make extra spicy.',
//   },
//   {
//     id: 4,
//     trackingId: '0256986330',
//     status: 'Preparing',
//     restaurantName: 'Suraya Fast Food',
//     dishArray: [
//       {
//         id: 1,
//         name: 'Manchurian with Fried Rice',
//         quanity: 2,
//         vegNonVeg: 'veg',
//         price: 170,
//       },
//       {
//         id: 2,
//         name: 'Rumali Roti',
//         quanity: 6,
//         vegNonVeg: 'veg',
//         price: 60,
//       },
//       {
//         id: 3,
//         name: 'Chicken Biriyani',
//         quanity: 1,
//         vegNonVeg: 'nonveg',
//         price: 280,
//       },
//     ],
//     total: 450,
//     billPayment: 'Unpaid',
//     cookinTiming:'20 min',
//     date: new Date(),
//     instructions:
//       ' Please make extra spicy, Please make extra spicy, Please make extra spicy, Please make extra spicy.',
//   },
// ];

export const orderHistory = [
  {
    id: '045',
    name: 'Rahul Garg ',
    status: 'Completed',
    date: new Date(),
    price: 180,
  },
  {
      id: '046',
      name: 'Rahul Garg ',
      status: 'Declined',
      date: new Date(),
      price: 180,
    },
    {
      id: '047',
      name: 'Rahul Garg ',
      status: 'Completed',
      date: new Date(),
      price: 180,
    },
    {
        id: '048',
        name: 'Rahul Garg ',
        status: 'Declined',
        date: new Date(),
        price: 180,
      },
      {
          id: '049',
          name: 'Rahul Garg ',
          status: 'Completed',
          date: new Date(),
          price: 180,
        },
        {
            id: '050',
            name: 'Rahul Garg ',
            status: 'Declined',
            date: new Date(),
            price: 180,
          },
];

export const restaurantOnOff = [
  {
    id: 0,
    title: 'Out of Stock',
  },
  {
    id: 1,
    title: 'Over Capacity',
  },
  {
    id: 2,
    title: 'Staffing Issues',
  },
  {
    id: 3,
    title: 'Closed for Maintenance',
  },
  {
    id: 4,
    title: 'Special Events or Holidays',
  },
  {
    id: 5,
    title: 'Other',
  },
];
