 export const TimingData = {data:[,
    {days_of_week: 0, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 0, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 1, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 1, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 2, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 3, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 4, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 5, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 6, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 6, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 7, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
    {days_of_week: 7, open_times: '15:02', close_time: '17:02', org_id: undefined, isEditDelete: false},
]}